// equipment.js – Ground unit equipment library
// Format: "Item Name" or { name: "Item Name", variants: ["V1", "V2"] }

var EQUIPMENT_LIBRARY_EXT = [
    "All Terrain Vehicle (ATV)",
    "All-Terrain Tracked Vehicle (A-TTV)",
    "Ammunition Carrier (AC)",
    "Amphibious Tracked Transport Carrier (ATTC)",
    "Anti-Ballistic Missile Defense Vehicle (ABM[D])",
    "Anti-Tank Vehicle (AT-V)",
    "Armored Ammunition Carrier (AAC)",
    "Armored Command Vehicle (ACV)",
    { name: "Armored Excavator", variants: ["Tracked", "Wheeled"] },
    "Armored Medical Vehicle (AMV)",
    "Armored Mine Clearing (AMC)",
    "Armored Personnel Carrier (APC)",
    "Armored Reconnaissance Vehicle (ARV)",
    { name: "Armored Recovery Vehicle", variants: ["Tracked", "Wheeled"] },
    "Armored Tractor",
    "Armored Train",
    { name: "Armored Vehicle Launched Bridge", variants: ["Tracked", "Wheeled"] },
    "Articulated Tracked Transport Vehicle (ATTV)",
    "Assault Breaching Vehicle (ABV)",
    "C4 Vehicle",
    "CBRN Defense Vehicle (CBRN-DV)",
    { name: "Combat Engineering Vehicle", variants: ["Tracked", "Wheeled"] },
    "Command & Control Vehicle",
    "Command Vehicle (CV)",
    "Communication Vehicle",
    { name: "Crane", variants: ["Tracked", "Wheeled"] },
    "Decontamination Vehicle",
    "Drilling Vehicle",
    { name: "Electronic Warfare Vehicle", variants: ["Heavy (EWV-H)", "Light (EWV-L)", "Medium (EWV-M)"] },
    { name: "Excavator", variants: ["Tracked", "Wheeled"] },
    "Floating Bridge",
    "Heavy Truck",
    "Heavy Utility Vehicle (HUV)",
    "Infantry Fighting Vehicle (IFV)",
    "Infantry Mobility Vehicle (IMV)",
    "Light Tactical Transporter (LTT)",
    "Light Tank (LT)",
    "Light Truck",
    "Light Utility Vehicle (LUV)",
    "Long-Range Air Defense Vehicle (LRAD)",
    "Main Battle Tank (MBT)",
    "Medical Vehicle (MV)",
    "Medium Utility Vehicle (MUV)",
    "Medium Truck",
    "Medium-Range Air Defense Vehicle (MRAD)",
    "Mine Clearing (MC)",
    { name: "Mine Resistant Ambush Protected (MRAP)", variants: ["Heavy (MRAP-H)", "Light (MRAP-L)", "Medium (MRAP-M)"] },
    "Minelayer",
    "Motorcycle",
    "Motorized Scooter (MS)",
    "Radar Vehicle",
    "Reconnaissance Vehicle (RV)",
    "Repair and Recovery Vehicle (RRV)",
    "Satellite Communication Vehicle",
    "Self-Propelled Gun (SPG)",
    "Self-Propelled Howitzer (SPH)",
    "Self-Propelled Mortar (SPM)",
    "Self-Propelled Multiple Launch Rocket System (SP-MLRS)",
    "Short-Range Air Defense Vehicle (SRAD)",
    "Smoke Vehicle",
    "SPG Ammunition Carrier (SPG-AC)",
    "Tank Transporter",
    "Tractor",
    "Train",
    "Trencher",
    "Unmanned Ground Vehicle (UGV)",
    { name: "Vehicle Launched Bridge", variants: ["Tracked", "Wheeled"] },

    // ---- Towed Artillery & Static Weapons ----
    { name: "Towed Howitzer", variants: ["Light (105mm)", "Medium (155mm)", "Heavy (203mm)"] },
    { name: "Towed Anti-Tank Gun", variants: ["57mm", "85mm", "100mm", "105mm"] },
    { name: "Towed Anti-Aircraft Gun", variants: ["23mm", "35mm", "57mm", "85mm"] },
    "Towed Rocket Launcher",
    "Towed Recoilless Rifle",
    "Coastal Defense Gun",
    "Railway Gun",

    // ---- Animal Transport ----
    "Horse (Riding)",
    "Horse (Draft)",
    "Mule / Donkey (Pack)",
    "Horse-Drawn Wagon",
    "Dog Sled / Pack Team",

    // ---- Watercraft ----
    "Assault Boat",
    "Pontoon Bridge Section",
    "Raft",
    "Landing Craft",
    "Patrol Boat",

    // ---- Personal Weapons / Small Arms ----
    { name: "Rifle", variants: ["Assault Rifle", "Battle Rifle", "Designated Marksman Rifle (DMR)", "Sniper Rifle", "Anti-Materiel Rifle"] },
    "Submachine Gun (SMG)",
    "Carbine",
    { name: "Machine Gun", variants: ["Light (LMG)", "General Purpose (GPMG)", "Heavy (HMG)"] },
    { name: "Pistol", variants: ["Standard", "Silenced"] },
    { name: "Shotgun", variants: ["Tactical", "Combat"] },
    { name: "Grenade Launcher", variants: ["Underbarrel", "Standalone", "Automatic"] },
    "Anti-Tank Guided Missile (ATGM)",
    "Man-Portable Air Defense System (MANPADS)",
    { name: "Rocket Launcher", variants: ["Anti-Tank (LAW/RPG)", "Anti-Bunker"] },
    "Recoilless Rifle (Man-Portable)",
    "Flamethrower",
    { name: "Mortar", variants: ["Light (60mm)", "Medium (81mm)", "Heavy (120mm)"] },
    { name: "Grenade", variants: ["Fragmentation", "Smoke", "Incendiary", "Stun"] },
    "Claymore Mine",
    "Satchel Charge",
    "Bayonet",
    "Combat Knife",

    // ---- Individual Equipment / Gear ----
    { name: "Radio Set", variants: ["Manpack", "Vehicular", "Handheld"] },
    "Satellite Terminal",
    "Field Telephone",
    "Binoculars",
    "Night Vision Goggles (NVG)",
    "Thermal Sight",
    { name: "Weapon Optic", variants: ["Telescopic", "Red Dot", "Holographic", "IR"] },
    "Laser Range Finder",
    "GPS / Navigation System",
    { name: "Body Armor", variants: ["Plate Carrier", "Tactical Vest", "Bomb Suit"] },
    { name: "Helmet", variants: ["Ballistic", "Bump", "Airframe"] },
    "Gas Mask / CBRN Mask",
    "Camouflage Net",
    "Smoke Screen Generator",
    "Field Kitchen",
    "Water Purification Unit",
    "Generator",
    "Fuel Bladder / Tanker",
    "Ammunition Resupply Crate",
    "Medical Kit / Trauma Bag",
    "Stretcher / Litter",
    { name: "Shelter", variants: ["Tent", "Bivouac", "Fighting Position"] },
    "Entrenching Tool (E-Tool)",
    "Pick / Mattock",
    "Barbed Wire Roll",
    "Sandbag Bundle",
    "Demolition Kit",
    "Searchlight",
    "Water Can (Jerry Can)",
    "Rucksack / Assault Pack",
    "Landmine (Anti-Personnel)",
    "Landmine (Anti-Tank)"
];